### ISSUE TITLE
Gem::ConflictError: Unable to activate ci_reporter_cucumber-1.0.2, because cucumber-2.4.0 conflicts with cucumber (~> 1.3.3)a

### ISSUE THREAD

**Issue by ghost** [ci-reporter/ci_reporter_cucumber#15] opened 2016-08-15 11:16 UTC
Hi,

I'm, trying to figure out what gems are required on top of cucumber and rake in order to use this ci reporter for cucumber. At the moment I'm getting an error about versions:

```
Gem::ConflictError: Unable to activate ci_reporter_cucumber-1.0.2, because cucumber-2.4.0 conflicts with cucumber (~> 1.3.3)a
```

Please could the maintainer advise? @nicksieger @shepmaster

**Comment by shepmaster** [comment] 2016-08-15 12:55
Yes, as discussed in #8, this gem is not currently compatible with Cucumber 2.0 and is waiting for someone who uses both to update the code appropriately.

Closing as a duplicate of #8.

BTW, there's no need to at-mention maintainers; maintainers get emails for issues regardless.

**Closed as completed by shepmaster** 2016-08-15 12:55 UTC
